@startuml
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor<<optional>> beige
  BackgroundColor<<test>> lightGreen
  BackgroundColor<<runtime>> lightBlue
  BackgroundColor<<provided>> lightGray
}
rectangle "junit-jupiter-api\n6.0.3" as org_junit_jupiter_junit_jupiter_api_jar_test<<test>>
rectangle "opentest4j\n1.3.0" as org_opentest4j_opentest4j_jar_test<<test>>
rectangle "junit-platform-commons\n6.0.3" as org_junit_platform_junit_platform_commons_jar_test<<test>>
rectangle "apiguardian-api\n1.1.2" as org_apiguardian_apiguardian_api_jar_test<<test>>
rectangle "jspecify\n1.0.1" as org_jspecify_jspecify_jar_test<<test>>
rectangle "junit-jupiter\n6.0.3" as org_junit_jupiter_junit_jupiter_jar_test<<test>>
rectangle "junit-jupiter-params\n6.0.3" as org_junit_jupiter_junit_jupiter_params_jar_test<<test>>
rectangle "junit-jupiter-engine\n6.0.3" as org_junit_jupiter_junit_jupiter_engine_jar_test<<test>>
rectangle "junit-platform-engine\n6.0.3" as org_junit_platform_junit_platform_engine_jar_test<<test>>
rectangle "archi-modeling-domain\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_modeling_domain_jar_compile
rectangle "archi-modeling-application\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_modeling_application_jar_compile
rectangle "archi-modeling-adapter-rest\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile
rectangle "jackson-databind\n3.1.5" as tools_jackson_core_jackson_databind_jar_compile
rectangle "jackson-annotations\n2.21" as com_fasterxml_jackson_core_jackson_annotations_jar_compile
rectangle "jackson-core\n3.1.5" as tools_jackson_core_jackson_core_jar_compile
rectangle "spring-boot-jackson\n4.1.1" as org_springframework_boot_spring_boot_jackson_jar_compile
rectangle "spring-boot-starter-jackson\n4.1.1" as org_springframework_boot_spring_boot_starter_jackson_jar_compile
rectangle "spring-boot-starter-web\n4.1.1" as org_springframework_boot_spring_boot_starter_web_jar_compile
rectangle "spring-boot-starter-tomcat-runtime\n4.1.1" as org_springframework_boot_spring_boot_starter_tomcat_runtime_jar_compile
rectangle "spring-boot-web-server\n4.1.1" as org_springframework_boot_spring_boot_web_server_jar_compile
rectangle "tomcat-embed-core\n11.0.24" as org_apache_tomcat_embed_tomcat_embed_core_jar_compile
rectangle "tomcat-embed-websocket\n11.0.24" as org_apache_tomcat_embed_tomcat_embed_websocket_jar_compile
rectangle "spring-boot-starter-tomcat\n4.1.1" as org_springframework_boot_spring_boot_starter_tomcat_jar_compile
rectangle "spring-boot-tomcat\n4.1.1" as org_springframework_boot_spring_boot_tomcat_jar_compile
rectangle "spring-core\n7.0.9" as org_springframework_spring_core_jar_compile
rectangle "commons-logging\n1.3.6" as commons_logging_commons_logging_jar_compile
rectangle "spring-boot\n4.1.1" as org_springframework_boot_spring_boot_jar_compile
rectangle "spring-context\n7.0.9" as org_springframework_spring_context_jar_compile
rectangle "spring-boot-http-converter\n4.1.1" as org_springframework_boot_spring_boot_http_converter_jar_compile
rectangle "spring-web\n7.0.9" as org_springframework_spring_web_jar_compile
rectangle "spring-beans\n7.0.9" as org_springframework_spring_beans_jar_compile
rectangle "micrometer-observation\n1.17.1" as io_micrometer_micrometer_observation_jar_compile
rectangle "micrometer-commons\n1.17.1" as io_micrometer_micrometer_commons_jar_compile
rectangle "spring-boot-webmvc\n4.1.1" as org_springframework_boot_spring_boot_webmvc_jar_compile
rectangle "spring-boot-servlet\n4.1.1" as org_springframework_boot_spring_boot_servlet_jar_compile
rectangle "spring-webmvc\n7.0.9" as org_springframework_spring_webmvc_jar_compile
rectangle "spring-aop\n7.0.9" as org_springframework_spring_aop_jar_compile
rectangle "spring-expression\n7.0.9" as org_springframework_spring_expression_jar_compile
rectangle "logback-classic\n1.5.38" as ch_qos_logback_logback_classic_jar_compile
rectangle "logback-core\n1.5.38" as ch_qos_logback_logback_core_jar_compile
rectangle "slf4j-api\n2.0.18" as org_slf4j_slf4j_api_jar_compile
rectangle "spring-boot-starter-logging\n4.1.1" as org_springframework_boot_spring_boot_starter_logging_jar_compile
rectangle "log4j-to-slf4j\n2.25.5" as org_apache_logging_log4j_log4j_to_slf4j_jar_compile
rectangle "log4j-api\n2.25.5" as org_apache_logging_log4j_log4j_api_jar_compile
rectangle "jul-to-slf4j\n2.0.18" as org_slf4j_jul_to_slf4j_jar_compile
rectangle "spring-boot-starter\n4.1.1" as org_springframework_boot_spring_boot_starter_jar_compile
rectangle "spring-boot-autoconfigure\n4.1.1" as org_springframework_boot_spring_boot_autoconfigure_jar_compile
rectangle "jakarta.annotation-api\n3.0.0" as jakarta_annotation_jakarta_annotation_api_jar_compile
rectangle "snakeyaml\n2.6" as org_yaml_snakeyaml_jar_compile
rectangle "spring-boot-starter-validation\n4.1.1" as org_springframework_boot_spring_boot_starter_validation_jar_compile
rectangle "spring-boot-validation\n4.1.1" as org_springframework_boot_spring_boot_validation_jar_compile
rectangle "tomcat-embed-el\n11.0.24" as org_apache_tomcat_embed_tomcat_embed_el_jar_compile
rectangle "hibernate-validator\n9.1.3.Final" as org_hibernate_validator_hibernate_validator_jar_compile
rectangle "jakarta.validation-api\n3.1.1" as jakarta_validation_jakarta_validation_api_jar_compile
rectangle "jboss-logging\n3.6.3.Final" as org_jboss_logging_jboss_logging_jar_compile
rectangle "classmate\n1.7.3" as com_fasterxml_classmate_jar_compile
rectangle "jspecify\n1.0.1" as org_jspecify_jspecify_jar_compile
rectangle "archi-modeling-adapter-persistence\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_modeling_adapter_persistence_jar_compile
rectangle "spring-boot-starter-data-jpa\n4.1.1" as org_springframework_boot_spring_boot_starter_data_jpa_jar_compile
rectangle "HikariCP\n7.0.2" as com_zaxxer_HikariCP_jar_compile
rectangle "spring-boot-starter-jdbc\n4.1.1" as org_springframework_boot_spring_boot_starter_jdbc_jar_compile
rectangle "spring-boot-data-commons\n4.1.1" as org_springframework_boot_spring_boot_data_commons_jar_compile
rectangle "spring-boot-persistence\n4.1.1" as org_springframework_boot_spring_boot_persistence_jar_compile
rectangle "spring-data-commons\n4.1.1" as org_springframework_data_spring_data_commons_jar_compile
rectangle "spring-boot-data-jpa\n4.1.1" as org_springframework_boot_spring_boot_data_jpa_jar_compile
rectangle "spring-boot-jpa\n4.1.1" as org_springframework_boot_spring_boot_jpa_jar_compile
rectangle "jakarta.persistence-api\n3.2.0" as jakarta_persistence_jakarta_persistence_api_jar_compile
rectangle "spring-boot-hibernate\n4.1.1" as org_springframework_boot_spring_boot_hibernate_jar_compile
rectangle "hibernate-core\n7.4.5.Final" as org_hibernate_orm_hibernate_core_jar_compile
rectangle "jakarta.transaction-api\n2.0.1" as jakarta_transaction_jakarta_transaction_api_jar_compile
rectangle "jboss-logging\n3.6.3.Final" as org_jboss_logging_jboss_logging_jar_runtime<<runtime>>
rectangle "hibernate-models\n1.1.1" as org_hibernate_models_hibernate_models_jar_runtime<<runtime>>
rectangle "byte-buddy\n1.18.11" as net_bytebuddy_byte_buddy_jar_runtime<<runtime>>
rectangle "jakarta.xml.bind-api\n4.0.5" as jakarta_xml_bind_jakarta_xml_bind_api_jar_runtime<<runtime>>
rectangle "jakarta.activation-api\n2.1.4" as jakarta_activation_jakarta_activation_api_jar_runtime<<runtime>>
rectangle "jaxb-core\n4.0.9" as org_glassfish_jaxb_jaxb_core_jar_runtime<<runtime>>
rectangle "angus-activation\n2.0.3" as org_eclipse_angus_angus_activation_jar_runtime<<runtime>>
rectangle "txw2\n4.0.9" as org_glassfish_jaxb_txw2_jar_runtime<<runtime>>
rectangle "istack-commons-runtime\n4.1.2" as com_sun_istack_istack_commons_runtime_jar_runtime<<runtime>>
rectangle "jaxb-runtime\n4.0.9" as org_glassfish_jaxb_jaxb_runtime_jar_runtime<<runtime>>
rectangle "jakarta.inject-api\n2.0.1" as jakarta_inject_jakarta_inject_api_jar_runtime<<runtime>>
rectangle "spring-orm\n7.0.9" as org_springframework_spring_orm_jar_compile
rectangle "spring-data-jpa\n4.1.1" as org_springframework_data_spring_data_jpa_jar_compile
rectangle "spring-tx\n7.0.9" as org_springframework_spring_tx_jar_compile
rectangle "antlr4-runtime\n4.13.2" as org_antlr_antlr4_runtime_jar_compile
rectangle "spring-aspects\n7.0.9" as org_springframework_spring_aspects_jar_compile
rectangle "aspectjweaver\n1.9.25.1" as org_aspectj_aspectjweaver_jar_compile
rectangle "spring-boot-jdbc\n4.1.1" as org_springframework_boot_spring_boot_jdbc_jar_compile
rectangle "spring-boot-sql\n4.1.1" as org_springframework_boot_spring_boot_sql_jar_compile
rectangle "spring-boot-transaction\n4.1.1" as org_springframework_boot_spring_boot_transaction_jar_compile
rectangle "spring-jdbc\n7.0.9" as org_springframework_spring_jdbc_jar_compile
rectangle "archi-interchange-domain\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_interchange_domain_jar_compile
rectangle "archi-interchange-application\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_interchange_application_jar_compile
rectangle "archi-interchange-adapter-rest\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile
rectangle "archi-interchange-adapter-persistence\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_interchange_adapter_persistence_jar_compile
rectangle "archi-advisor-domain\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_advisor_domain_jar_compile
rectangle "archi-advisor-application\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_advisor_application_jar_compile
rectangle "archi-advisor-adapter-rest\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile
rectangle "archi-advisor-adapter-persistence\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_advisor_adapter_persistence_jar_compile
rectangle "archi-bootstrap\n1.0-SNAPSHOT" as uz_salvadore_hamkorbank_archi_bootstrap_jar_compile
rectangle "spring-boot-starter-actuator\n4.1.1" as org_springframework_boot_spring_boot_starter_actuator_jar_compile
rectangle "spring-boot-micrometer-metrics\n4.1.1" as org_springframework_boot_spring_boot_micrometer_metrics_jar_compile
rectangle "spring-boot-micrometer-observation\n4.1.1" as org_springframework_boot_spring_boot_micrometer_observation_jar_compile
rectangle "spring-boot-starter-micrometer-metrics\n4.1.1" as org_springframework_boot_spring_boot_starter_micrometer_metrics_jar_compile
rectangle "spring-boot-actuator-autoconfigure\n4.1.1" as org_springframework_boot_spring_boot_actuator_autoconfigure_jar_compile
rectangle "spring-boot-actuator\n4.1.1" as org_springframework_boot_spring_boot_actuator_jar_compile
rectangle "spring-boot-health\n4.1.1" as org_springframework_boot_spring_boot_health_jar_compile
rectangle "micrometer-jakarta9\n1.17.1" as io_micrometer_micrometer_jakarta9_jar_compile
rectangle "micrometer-registry-prometheus\n1.17.1" as io_micrometer_micrometer_registry_prometheus_jar_runtime<<runtime>>
rectangle "micrometer-core\n1.17.1" as io_micrometer_micrometer_core_jar_compile
rectangle "HdrHistogram\n2.2.2" as org_hdrhistogram_HdrHistogram_jar_runtime<<runtime>>
rectangle "prometheus-metrics-core\n1.7.0" as io_prometheus_prometheus_metrics_core_jar_runtime<<runtime>>
rectangle "prometheus-metrics-model\n1.7.0" as io_prometheus_prometheus_metrics_model_jar_runtime<<runtime>>
rectangle "prometheus-metrics-config\n1.7.0" as io_prometheus_prometheus_metrics_config_jar_runtime<<runtime>>
rectangle "prometheus-metrics-tracer-common\n1.7.0" as io_prometheus_prometheus_metrics_tracer_common_jar_runtime<<runtime>>
rectangle "prometheus-metrics-exposition-formats\n1.7.0" as io_prometheus_prometheus_metrics_exposition_formats_jar_runtime<<runtime>>
rectangle "prometheus-metrics-exposition-textformats\n1.7.0" as io_prometheus_prometheus_metrics_exposition_textformats_jar_runtime<<runtime>>
rectangle "spring-boot-security\n4.1.1" as org_springframework_boot_spring_boot_security_jar_compile
rectangle "spring-security-config\n7.1.1" as org_springframework_security_spring_security_config_jar_compile
rectangle "spring-boot-starter-security\n4.1.1" as org_springframework_boot_spring_boot_starter_security_jar_compile
rectangle "spring-security-oauth2-jose\n7.1.1" as org_springframework_security_spring_security_oauth2_jose_jar_compile
rectangle "spring-security-oauth2-core\n7.1.1" as org_springframework_security_spring_security_oauth2_core_jar_compile
rectangle "nimbus-jose-jwt\n10.9.1" as com_nimbusds_nimbus_jose_jwt_jar_compile
rectangle "spring-boot-security-oauth2-resource-server\n4.1.1" as org_springframework_boot_spring_boot_security_oauth2_resource_server_jar_compile
rectangle "spring-security-oauth2-resource-server\n7.1.1" as org_springframework_security_spring_security_oauth2_resource_server_jar_compile
rectangle "spring-boot-starter-oauth2-resource-server\n4.1.1" as org_springframework_boot_spring_boot_starter_oauth2_resource_server_jar_compile
rectangle "spring-boot-flyway\n4.1.1" as org_springframework_boot_spring_boot_flyway_jar_compile
rectangle "flyway-core\n12.4.0" as org_flywaydb_flyway_core_jar_compile
rectangle "flyway-database-postgresql\n12.4.0" as org_flywaydb_flyway_database_postgresql_jar_compile
rectangle "postgresql\n42.7.13" as org_postgresql_postgresql_jar_runtime<<runtime>>
rectangle "checker-qual\n3.55.1" as org_checkerframework_checker_qual_jar_runtime<<runtime>>
rectangle "archunit-junit5-api\n1.5.1" as com_tngtech_archunit_archunit_junit5_api_jar_test<<test>>
rectangle "archunit\n1.5.1" as com_tngtech_archunit_archunit_jar_test<<test>>
rectangle "archunit-junit5\n1.5.1" as com_tngtech_archunit_archunit_junit5_jar_test<<test>>
rectangle "archunit-junit5-engine\n1.5.1" as com_tngtech_archunit_archunit_junit5_engine_jar_test<<test>>
rectangle "archunit-junit5-engine-api\n1.5.1" as com_tngtech_archunit_archunit_junit5_engine_api_jar_test<<test>>
rectangle "spring-boot-starter-test\n4.1.1" as org_springframework_boot_spring_boot_starter_test_jar_test<<test>>
rectangle "spring-boot-test\n4.1.1" as org_springframework_boot_spring_boot_test_jar_test<<test>>
rectangle "spring-boot-test-autoconfigure\n4.1.1" as org_springframework_boot_spring_boot_test_autoconfigure_jar_test<<test>>
rectangle "json-path\n2.10.0" as com_jayway_jsonpath_json_path_jar_test<<test>>
rectangle "accessors-smart\n2.6.0" as net_minidev_accessors_smart_jar_test<<test>>
rectangle "asm\n9.7.1" as org_ow2_asm_asm_jar_test<<test>>
rectangle "json-smart\n2.6.0" as net_minidev_json_smart_jar_test<<test>>
rectangle "assertj-core\n3.27.7" as org_assertj_assertj_core_jar_test<<test>>
rectangle "awaitility\n4.3.0" as org_awaitility_awaitility_jar_test<<test>>
rectangle "hamcrest\n3.0" as org_hamcrest_hamcrest_jar_test<<test>>
rectangle "mockito-core\n5.23.0" as org_mockito_mockito_core_jar_test<<test>>
rectangle "byte-buddy-agent\n1.18.11" as net_bytebuddy_byte_buddy_agent_jar_test<<test>>
rectangle "objenesis\n3.3" as org_objenesis_objenesis_jar_test<<test>>
rectangle "mockito-junit-jupiter\n5.23.0" as org_mockito_mockito_junit_jupiter_jar_test<<test>>
rectangle "jsonassert\n1.5.3" as org_skyscreamer_jsonassert_jar_test<<test>>
rectangle "android-json\n0.0.20131108.vaadin1" as com_vaadin_external_google_android_json_jar_test<<test>>
rectangle "spring-test\n7.0.9" as org_springframework_spring_test_jar_test<<test>>
rectangle "xmlunit-core\n2.11.0" as org_xmlunit_xmlunit_core_jar_test<<test>>
rectangle "spring-boot-starter-webmvc-test\n4.1.1" as org_springframework_boot_spring_boot_starter_webmvc_test_jar_test<<test>>
rectangle "spring-boot-starter-jackson-test\n4.1.1" as org_springframework_boot_spring_boot_starter_jackson_test_jar_test<<test>>
rectangle "spring-boot-starter-webmvc\n4.1.1" as org_springframework_boot_spring_boot_starter_webmvc_jar_test<<test>>
rectangle "spring-boot-webmvc-test\n4.1.1" as org_springframework_boot_spring_boot_webmvc_test_jar_test<<test>>
rectangle "spring-boot-resttestclient\n4.1.1" as org_springframework_boot_spring_boot_resttestclient_jar_test<<test>>
rectangle "spring-security-core\n7.1.1" as org_springframework_security_spring_security_core_jar_compile
rectangle "spring-security-crypto\n7.1.1" as org_springframework_security_spring_security_crypto_jar_compile
rectangle "spring-security-test\n7.1.1" as org_springframework_security_spring_security_test_jar_test<<test>>
rectangle "spring-security-web\n7.1.1" as org_springframework_security_spring_security_web_jar_compile
rectangle "commons-compress\n1.28.0" as org_apache_commons_commons_compress_jar_test<<test>>
rectangle "commons-codec\n1.21.0" as commons_codec_commons_codec_jar_test<<test>>
rectangle "commons-io\n2.20.0" as commons_io_commons_io_jar_test<<test>>
rectangle "commons-lang3\n3.20.0" as org_apache_commons_commons_lang3_jar_test<<test>>
rectangle "testcontainers\n2.0.5" as org_testcontainers_testcontainers_jar_test<<test>>
rectangle "duct-tape\n1.0.8" as org_rnorth_duct_tape_duct_tape_jar_test<<test>>
rectangle "annotations\n17.0.0" as org_jetbrains_annotations_jar_test<<test>>
rectangle "docker-java-api\n3.7.1" as com_github_docker_java_docker_java_api_jar_test<<test>>
rectangle "docker-java-transport-zerodep\n3.7.1" as com_github_docker_java_docker_java_transport_zerodep_jar_test<<test>>
rectangle "docker-java-transport\n3.7.1" as com_github_docker_java_docker_java_transport_jar_test<<test>>
rectangle "jna\n5.18.1" as net_java_dev_jna_jna_jar_test<<test>>
rectangle "testcontainers-database-commons\n2.0.5" as org_testcontainers_testcontainers_database_commons_jar_test<<test>>
rectangle "testcontainers-jdbc\n2.0.5" as org_testcontainers_testcontainers_jdbc_jar_test<<test>>
rectangle "testcontainers-postgresql\n2.0.5" as org_testcontainers_testcontainers_postgresql_jar_test<<test>>
org_junit_jupiter_junit_jupiter_api_jar_test -[#000000]-> org_opentest4j_opentest4j_jar_test
org_junit_jupiter_junit_jupiter_api_jar_test -[#000000]-> org_junit_platform_junit_platform_commons_jar_test
org_junit_jupiter_junit_jupiter_api_jar_test -[#000000]-> org_apiguardian_apiguardian_api_jar_test
org_junit_jupiter_junit_jupiter_api_jar_test -[#000000]-> org_jspecify_jspecify_jar_test
org_junit_jupiter_junit_jupiter_jar_test -[#000000]-> org_junit_jupiter_junit_jupiter_api_jar_test
org_junit_jupiter_junit_jupiter_jar_test -[#000000]-> org_junit_jupiter_junit_jupiter_params_jar_test
org_junit_jupiter_junit_jupiter_engine_jar_test -[#000000]-> org_junit_platform_junit_platform_engine_jar_test
org_junit_jupiter_junit_jupiter_jar_test -[#000000]-> org_junit_jupiter_junit_jupiter_engine_jar_test
uz_salvadore_hamkorbank_archi_modeling_domain_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_modeling_application_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_domain_jar_compile
uz_salvadore_hamkorbank_archi_modeling_application_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_application_jar_compile
tools_jackson_core_jackson_databind_jar_compile -[#000000]-> com_fasterxml_jackson_core_jackson_annotations_jar_compile
tools_jackson_core_jackson_databind_jar_compile -[#000000]-> tools_jackson_core_jackson_core_jar_compile
org_springframework_boot_spring_boot_jackson_jar_compile -[#000000]-> tools_jackson_core_jackson_databind_jar_compile
org_springframework_boot_spring_boot_starter_jackson_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jackson_jar_compile
org_springframework_boot_spring_boot_starter_web_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_jackson_jar_compile
org_springframework_boot_spring_boot_starter_tomcat_runtime_jar_compile -[#000000]-> org_springframework_boot_spring_boot_web_server_jar_compile
org_springframework_boot_spring_boot_starter_tomcat_runtime_jar_compile -[#000000]-> org_apache_tomcat_embed_tomcat_embed_core_jar_compile
org_springframework_boot_spring_boot_starter_tomcat_runtime_jar_compile -[#000000]-> org_apache_tomcat_embed_tomcat_embed_websocket_jar_compile
org_springframework_boot_spring_boot_starter_tomcat_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_tomcat_runtime_jar_compile
org_springframework_boot_spring_boot_starter_tomcat_jar_compile -[#000000]-> org_springframework_boot_spring_boot_tomcat_jar_compile
org_springframework_boot_spring_boot_starter_web_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_tomcat_jar_compile
org_springframework_spring_core_jar_compile -[#000000]-> commons_logging_commons_logging_jar_compile
org_springframework_boot_spring_boot_jar_compile -[#000000]-> org_springframework_spring_core_jar_compile
org_springframework_boot_spring_boot_jar_compile -[#000000]-> org_springframework_spring_context_jar_compile
org_springframework_boot_spring_boot_http_converter_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jar_compile
org_springframework_spring_web_jar_compile -[#000000]-> org_springframework_spring_beans_jar_compile
io_micrometer_micrometer_observation_jar_compile -[#000000]-> io_micrometer_micrometer_commons_jar_compile
org_springframework_spring_web_jar_compile -[#000000]-> io_micrometer_micrometer_observation_jar_compile
org_springframework_boot_spring_boot_http_converter_jar_compile -[#000000]-> org_springframework_spring_web_jar_compile
org_springframework_boot_spring_boot_starter_web_jar_compile -[#000000]-> org_springframework_boot_spring_boot_http_converter_jar_compile
org_springframework_boot_spring_boot_webmvc_jar_compile -[#000000]-> org_springframework_boot_spring_boot_servlet_jar_compile
org_springframework_spring_webmvc_jar_compile -[#000000]-> org_springframework_spring_aop_jar_compile
org_springframework_spring_webmvc_jar_compile -[#000000]-> org_springframework_spring_expression_jar_compile
org_springframework_boot_spring_boot_webmvc_jar_compile -[#000000]-> org_springframework_spring_webmvc_jar_compile
org_springframework_boot_spring_boot_starter_web_jar_compile -[#000000]-> org_springframework_boot_spring_boot_webmvc_jar_compile
uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_web_jar_compile
ch_qos_logback_logback_classic_jar_compile -[#000000]-> ch_qos_logback_logback_core_jar_compile
ch_qos_logback_logback_classic_jar_compile -[#000000]-> org_slf4j_slf4j_api_jar_compile
org_springframework_boot_spring_boot_starter_logging_jar_compile -[#000000]-> ch_qos_logback_logback_classic_jar_compile
org_apache_logging_log4j_log4j_to_slf4j_jar_compile -[#000000]-> org_apache_logging_log4j_log4j_api_jar_compile
org_springframework_boot_spring_boot_starter_logging_jar_compile -[#000000]-> org_apache_logging_log4j_log4j_to_slf4j_jar_compile
org_springframework_boot_spring_boot_starter_logging_jar_compile -[#000000]-> org_slf4j_jul_to_slf4j_jar_compile
org_springframework_boot_spring_boot_starter_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_logging_jar_compile
org_springframework_boot_spring_boot_starter_jar_compile -[#000000]-> org_springframework_boot_spring_boot_autoconfigure_jar_compile
org_springframework_boot_spring_boot_starter_jar_compile -[#000000]-> jakarta_annotation_jakarta_annotation_api_jar_compile
org_springframework_boot_spring_boot_starter_jar_compile -[#000000]-> org_yaml_snakeyaml_jar_compile
org_springframework_boot_spring_boot_starter_validation_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_jar_compile
org_springframework_boot_spring_boot_validation_jar_compile -[#000000]-> org_apache_tomcat_embed_tomcat_embed_el_jar_compile
org_hibernate_validator_hibernate_validator_jar_compile -[#000000]-> jakarta_validation_jakarta_validation_api_jar_compile
org_hibernate_validator_hibernate_validator_jar_compile -[#000000]-> org_jboss_logging_jboss_logging_jar_compile
org_hibernate_validator_hibernate_validator_jar_compile -[#000000]-> com_fasterxml_classmate_jar_compile
org_springframework_boot_spring_boot_validation_jar_compile -[#000000]-> org_hibernate_validator_hibernate_validator_jar_compile
org_springframework_boot_spring_boot_starter_validation_jar_compile -[#000000]-> org_springframework_boot_spring_boot_validation_jar_compile
uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_validation_jar_compile
org_junit_jupiter_junit_jupiter_api_jar_test -[#000000]-> org_jspecify_jspecify_jar_compile
uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_modeling_adapter_persistence_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_application_jar_compile
org_springframework_boot_spring_boot_starter_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_jar_compile
com_zaxxer_HikariCP_jar_compile -[#000000]-> org_slf4j_slf4j_api_jar_compile
org_springframework_boot_spring_boot_starter_jdbc_jar_compile -[#000000]-> com_zaxxer_HikariCP_jar_compile
org_springframework_boot_spring_boot_starter_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_jdbc_jar_compile
org_springframework_boot_spring_boot_data_commons_jar_compile -[#000000]-> org_springframework_boot_spring_boot_persistence_jar_compile
org_springframework_boot_spring_boot_data_commons_jar_compile -[#000000]-> org_springframework_data_spring_data_commons_jar_compile
org_springframework_boot_spring_boot_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_data_commons_jar_compile
org_springframework_boot_spring_boot_jpa_jar_compile -[#000000]-> jakarta_persistence_jakarta_persistence_api_jar_compile
org_springframework_boot_spring_boot_hibernate_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jpa_jar_compile
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> jakarta_transaction_jakarta_transaction_api_jar_compile
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> org_jboss_logging_jboss_logging_jar_runtime
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> org_hibernate_models_hibernate_models_jar_runtime
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> net_bytebuddy_byte_buddy_jar_runtime
jakarta_xml_bind_jakarta_xml_bind_api_jar_runtime -[#000000]-> jakarta_activation_jakarta_activation_api_jar_runtime
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> jakarta_xml_bind_jakarta_xml_bind_api_jar_runtime
org_glassfish_jaxb_jaxb_core_jar_runtime -[#000000]-> org_eclipse_angus_angus_activation_jar_runtime
org_glassfish_jaxb_jaxb_core_jar_runtime -[#000000]-> org_glassfish_jaxb_txw2_jar_runtime
org_glassfish_jaxb_jaxb_core_jar_runtime -[#000000]-> com_sun_istack_istack_commons_runtime_jar_runtime
org_glassfish_jaxb_jaxb_runtime_jar_runtime -[#000000]-> org_glassfish_jaxb_jaxb_core_jar_runtime
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> org_glassfish_jaxb_jaxb_runtime_jar_runtime
org_hibernate_orm_hibernate_core_jar_compile -[#000000]-> jakarta_inject_jakarta_inject_api_jar_runtime
org_springframework_boot_spring_boot_hibernate_jar_compile -[#000000]-> org_hibernate_orm_hibernate_core_jar_compile
org_springframework_boot_spring_boot_hibernate_jar_compile -[#000000]-> org_springframework_spring_orm_jar_compile
org_springframework_boot_spring_boot_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_hibernate_jar_compile
org_springframework_spring_context_jar_compile -[#000000]-> org_springframework_spring_expression_jar_compile
org_springframework_spring_context_jar_compile -[#000000]-> io_micrometer_micrometer_observation_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_springframework_spring_context_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_springframework_spring_aop_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_springframework_spring_tx_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_springframework_spring_beans_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_springframework_spring_core_jar_compile
org_springframework_data_spring_data_jpa_jar_compile -[#000000]-> org_antlr_antlr4_runtime_jar_compile
org_springframework_boot_spring_boot_data_jpa_jar_compile -[#000000]-> org_springframework_data_spring_data_jpa_jar_compile
org_springframework_spring_aspects_jar_compile -[#000000]-> org_aspectj_aspectjweaver_jar_compile
org_springframework_boot_spring_boot_data_jpa_jar_compile -[#000000]-> org_springframework_spring_aspects_jar_compile
org_springframework_boot_spring_boot_starter_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_data_jpa_jar_compile
org_springframework_boot_spring_boot_jdbc_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jar_compile
org_springframework_boot_spring_boot_jdbc_jar_compile -[#000000]-> org_springframework_boot_spring_boot_sql_jar_compile
org_springframework_boot_spring_boot_jdbc_jar_compile -[#000000]-> org_springframework_boot_spring_boot_transaction_jar_compile
org_springframework_boot_spring_boot_jdbc_jar_compile -[#000000]-> org_springframework_spring_jdbc_jar_compile
org_springframework_boot_spring_boot_starter_data_jpa_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jdbc_jar_compile
uz_salvadore_hamkorbank_archi_modeling_adapter_persistence_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_data_jpa_jar_compile
uz_salvadore_hamkorbank_archi_modeling_adapter_persistence_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_interchange_domain_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_interchange_application_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_interchange_domain_jar_compile
uz_salvadore_hamkorbank_archi_interchange_application_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_application_jar_compile
uz_salvadore_hamkorbank_archi_interchange_application_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_interchange_application_jar_compile
uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_web_jar_compile
uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_validation_jar_compile
uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_interchange_adapter_persistence_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_interchange_application_jar_compile
uz_salvadore_hamkorbank_archi_interchange_adapter_persistence_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_data_jpa_jar_compile
uz_salvadore_hamkorbank_archi_interchange_adapter_persistence_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_advisor_domain_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_advisor_application_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_advisor_domain_jar_compile
uz_salvadore_hamkorbank_archi_advisor_application_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_advisor_application_jar_compile
uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_web_jar_compile
uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_validation_jar_compile
uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_advisor_adapter_persistence_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_advisor_application_jar_compile
uz_salvadore_hamkorbank_archi_advisor_adapter_persistence_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_data_jpa_jar_compile
uz_salvadore_hamkorbank_archi_advisor_adapter_persistence_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_adapter_rest_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_modeling_adapter_persistence_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_interchange_adapter_rest_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_interchange_adapter_persistence_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_advisor_adapter_rest_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> uz_salvadore_hamkorbank_archi_advisor_adapter_persistence_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_jar_compile
org_springframework_boot_spring_boot_micrometer_metrics_jar_compile -[#000000]-> org_springframework_boot_spring_boot_micrometer_observation_jar_compile
org_springframework_boot_spring_boot_starter_micrometer_metrics_jar_compile -[#000000]-> org_springframework_boot_spring_boot_micrometer_metrics_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_micrometer_metrics_jar_compile
org_springframework_boot_spring_boot_actuator_autoconfigure_jar_compile -[#000000]-> org_springframework_boot_spring_boot_actuator_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> org_springframework_boot_spring_boot_actuator_autoconfigure_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> org_springframework_boot_spring_boot_health_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> io_micrometer_micrometer_observation_jar_compile
org_springframework_boot_spring_boot_starter_actuator_jar_compile -[#000000]-> io_micrometer_micrometer_jakarta9_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_actuator_jar_compile
io_micrometer_micrometer_registry_prometheus_jar_runtime -[#000000]-> org_jspecify_jspecify_jar_compile
io_micrometer_micrometer_core_jar_compile -[#000000]-> org_hdrhistogram_HdrHistogram_jar_runtime
io_micrometer_micrometer_registry_prometheus_jar_runtime -[#000000]-> io_micrometer_micrometer_core_jar_compile
io_prometheus_prometheus_metrics_core_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_model_jar_runtime
io_prometheus_prometheus_metrics_core_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_config_jar_runtime
io_micrometer_micrometer_registry_prometheus_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_core_jar_runtime
io_micrometer_micrometer_registry_prometheus_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_tracer_common_jar_runtime
io_prometheus_prometheus_metrics_exposition_formats_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_exposition_textformats_jar_runtime
io_micrometer_micrometer_registry_prometheus_jar_runtime -[#000000]-> io_prometheus_prometheus_metrics_exposition_formats_jar_runtime
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> io_micrometer_micrometer_registry_prometheus_jar_runtime
org_springframework_boot_spring_boot_security_jar_compile -[#000000]-> org_springframework_security_spring_security_config_jar_compile
org_springframework_boot_spring_boot_starter_security_jar_compile -[#000000]-> org_springframework_boot_spring_boot_security_jar_compile
org_springframework_spring_aop_jar_compile -[#000000]-> org_springframework_spring_beans_jar_compile
org_springframework_boot_spring_boot_starter_security_jar_compile -[#000000]-> org_springframework_spring_aop_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_security_jar_compile
org_springframework_security_spring_security_oauth2_jose_jar_compile -[#000000]-> org_springframework_security_spring_security_oauth2_core_jar_compile
org_springframework_security_spring_security_oauth2_jose_jar_compile -[#000000]-> com_nimbusds_nimbus_jose_jwt_jar_compile
org_springframework_boot_spring_boot_security_oauth2_resource_server_jar_compile -[#000000]-> org_springframework_security_spring_security_oauth2_jose_jar_compile
org_springframework_boot_spring_boot_security_oauth2_resource_server_jar_compile -[#000000]-> org_springframework_security_spring_security_oauth2_resource_server_jar_compile
org_springframework_boot_spring_boot_starter_oauth2_resource_server_jar_compile -[#000000]-> org_springframework_boot_spring_boot_security_oauth2_resource_server_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_oauth2_resource_server_jar_compile
org_springframework_boot_spring_boot_transaction_jar_compile -[#000000]-> org_springframework_boot_spring_boot_persistence_jar_compile
org_springframework_boot_spring_boot_transaction_jar_compile -[#000000]-> org_springframework_spring_tx_jar_compile
org_springframework_boot_spring_boot_flyway_jar_compile -[#000000]-> org_springframework_boot_spring_boot_jdbc_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_flyway_jar_compile
org_flywaydb_flyway_core_jar_compile -[#000000]-> tools_jackson_core_jackson_databind_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_flywaydb_flyway_core_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_flywaydb_flyway_database_postgresql_jar_compile
org_postgresql_postgresql_jar_runtime -[#000000]-> org_checkerframework_checker_qual_jar_runtime
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_postgresql_postgresql_jar_runtime
com_tngtech_archunit_archunit_junit5_api_jar_test -[#000000]-> com_tngtech_archunit_archunit_jar_test
com_tngtech_archunit_archunit_junit5_jar_test -[#000000]-> com_tngtech_archunit_archunit_junit5_api_jar_test
com_tngtech_archunit_archunit_junit5_engine_jar_test -[#000000]-> com_tngtech_archunit_archunit_junit5_engine_api_jar_test
com_tngtech_archunit_archunit_junit5_jar_test -[#000000]-> com_tngtech_archunit_archunit_junit5_engine_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> com_tngtech_archunit_archunit_junit5_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_test_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_test_autoconfigure_jar_test
com_jayway_jsonpath_json_path_jar_test -[#000000]-> org_slf4j_slf4j_api_jar_compile
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> com_jayway_jsonpath_json_path_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> jakarta_xml_bind_jakarta_xml_bind_api_jar_runtime
net_minidev_accessors_smart_jar_test -[#000000]-> org_ow2_asm_asm_jar_test
net_minidev_json_smart_jar_test -[#000000]-> net_minidev_accessors_smart_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> net_minidev_json_smart_jar_test
org_assertj_assertj_core_jar_test -[#000000]-> net_bytebuddy_byte_buddy_jar_runtime
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_assertj_assertj_core_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_awaitility_awaitility_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_hamcrest_hamcrest_jar_test
org_mockito_mockito_core_jar_test -[#000000]-> net_bytebuddy_byte_buddy_agent_jar_test
org_mockito_mockito_core_jar_test -[#000000]-> org_objenesis_objenesis_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_mockito_mockito_core_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_mockito_mockito_junit_jupiter_jar_test
org_skyscreamer_jsonassert_jar_test -[#000000]-> com_vaadin_external_google_android_json_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_skyscreamer_jsonassert_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_springframework_spring_core_jar_compile
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_springframework_spring_test_jar_test
org_springframework_boot_spring_boot_starter_test_jar_test -[#000000]-> org_xmlunit_xmlunit_core_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_test_jar_test
org_springframework_boot_spring_boot_starter_webmvc_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_starter_jackson_test_jar_test
org_springframework_boot_spring_boot_starter_webmvc_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_starter_webmvc_jar_test
org_springframework_boot_spring_boot_webmvc_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_web_server_jar_compile
org_springframework_boot_spring_boot_starter_webmvc_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_webmvc_test_jar_test
org_springframework_boot_spring_boot_resttestclient_jar_test -[#000000]-> org_springframework_spring_web_jar_compile
org_springframework_boot_spring_boot_starter_webmvc_test_jar_test -[#000000]-> org_springframework_boot_spring_boot_resttestclient_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_boot_spring_boot_starter_webmvc_test_jar_test
org_springframework_security_spring_security_core_jar_compile -[#000000]-> org_springframework_security_spring_security_crypto_jar_compile
org_springframework_security_spring_security_core_jar_compile -[#000000]-> org_springframework_spring_expression_jar_compile
org_springframework_security_spring_security_test_jar_test -[#000000]-> org_springframework_security_spring_security_core_jar_compile
org_springframework_security_spring_security_test_jar_test -[#000000]-> org_springframework_security_spring_security_web_jar_compile
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_springframework_security_spring_security_test_jar_test
org_apache_commons_commons_compress_jar_test -[#000000]-> commons_codec_commons_codec_jar_test
org_apache_commons_commons_compress_jar_test -[#000000]-> commons_io_commons_io_jar_test
org_apache_commons_commons_compress_jar_test -[#000000]-> org_apache_commons_commons_lang3_jar_test
org_testcontainers_testcontainers_jar_test -[#000000]-> org_apache_commons_commons_compress_jar_test
org_rnorth_duct_tape_duct_tape_jar_test -[#000000]-> org_jetbrains_annotations_jar_test
org_testcontainers_testcontainers_jar_test -[#000000]-> org_rnorth_duct_tape_duct_tape_jar_test
org_testcontainers_testcontainers_jar_test -[#000000]-> com_github_docker_java_docker_java_api_jar_test
com_github_docker_java_docker_java_transport_zerodep_jar_test -[#000000]-> com_github_docker_java_docker_java_transport_jar_test
com_github_docker_java_docker_java_transport_zerodep_jar_test -[#000000]-> net_java_dev_jna_jna_jar_test
org_testcontainers_testcontainers_jar_test -[#000000]-> com_github_docker_java_docker_java_transport_zerodep_jar_test
org_testcontainers_testcontainers_database_commons_jar_test -[#000000]-> org_testcontainers_testcontainers_jar_test
org_testcontainers_testcontainers_jdbc_jar_test -[#000000]-> org_testcontainers_testcontainers_database_commons_jar_test
org_testcontainers_testcontainers_postgresql_jar_test -[#000000]-> org_testcontainers_testcontainers_jdbc_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_testcontainers_testcontainers_postgresql_jar_test
uz_salvadore_hamkorbank_archi_bootstrap_jar_compile -[#000000]-> org_junit_jupiter_junit_jupiter_jar_test
@enduml